version: "2"
services:
  my-wpdb:
    image: t0p0112/mariadbcont
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: topo112
  my-wp:
    image: t0p0112/wordpresscont
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    links:
      - my-wpdb:mysql
    environment:
      WORDPRESS_DB_PASSWORD: topo112
  myphp:
    image: t0p0112/phpmyadmincont
    depends_on:
      - my-wpdb
    ports:
      - "443:80"
    links:
      - my-wpdb:mysql
    environment:
      PMA_HOST: my-wpdb
      
